# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'toolsbox.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpinBox, QSplitter, QTextEdit, QVBoxLayout,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(984, 640)
        Form.setMinimumSize(QSize(984, 640))
        Form.setMaximumSize(QSize(984, 640))
        icon = QIcon()
        icon.addFile(u"image/logo1.ico", QSize(), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.but_cls_logtotext_2 = QPushButton(Form)
        self.but_cls_logtotext_2.setObjectName(u"but_cls_logtotext_2")
        self.but_cls_logtotext_2.setGeometry(QRect(925, 590, 25, 24))
        self.but_save_logtotext = QPushButton(Form)
        self.but_save_logtotext.setObjectName(u"but_save_logtotext")
        self.but_save_logtotext.setEnabled(False)
        self.but_save_logtotext.setGeometry(QRect(895, 590, 25, 24))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(490, 105, 79, 16))
        self.but_cls_kwsms = QPushButton(Form)
        self.but_cls_kwsms.setObjectName(u"but_cls_kwsms")
        self.but_cls_kwsms.setEnabled(True)
        self.but_cls_kwsms.setGeometry(QRect(925, 320, 24, 24))
        self.but_cls_kwsms.setMaximumSize(QSize(25, 25))
        self.but_wallet = QPushButton(Form)
        self.but_wallet.setObjectName(u"but_wallet")
        self.but_wallet.setEnabled(False)
        self.but_wallet.setGeometry(QRect(430, 305, 50, 51))
        self.print_1 = QTextEdit(Form)
        self.print_1.setObjectName(u"print_1")
        self.print_1.setGeometry(QRect(6, 100, 475, 111))
        self.print_1.setReadOnly(True)
        self.print_2 = QTextEdit(Form)
        self.print_2.setObjectName(u"print_2")
        self.print_2.setGeometry(QRect(490, 5, 491, 96))
        self.print_2.setReadOnly(True)
        self.chk_translate = QCheckBox(Form)
        self.chk_translate.setObjectName(u"chk_translate")
        self.chk_translate.setEnabled(True)
        self.chk_translate.setGeometry(QRect(275, 330, 80, 20))
        self.chk_taici = QCheckBox(Form)
        self.chk_taici.setObjectName(u"chk_taici")
        self.chk_taici.setGeometry(QRect(275, 310, 71, 20))
        self.chk_taici.setAutoFillBackground(True)
        self.chk_taici.setTristate(False)
        self.pushButton_11 = QPushButton(Form)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(245, 310, 20, 20))
        self.pushButton_11.setMaximumSize(QSize(20, 20))
        self.print_4 = QTextEdit(Form)
        self.print_4.setObjectName(u"print_4")
        self.print_4.setGeometry(QRect(6, 220, 475, 81))
        self.but_daiban = QPushButton(Form)
        self.but_daiban.setObjectName(u"but_daiban")
        self.but_daiban.setGeometry(QRect(245, 330, 20, 20))
        self.splitter_3 = QSplitter(Form)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(9, 360, 971, 24))
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(self.splitter_3)
        self.label_3.setObjectName(u"label_3")
        self.splitter_3.addWidget(self.label_3)
        self.cmbox_activation = QComboBox(self.splitter_3)
        self.cmbox_activation.setObjectName(u"cmbox_activation")
        self.splitter_3.addWidget(self.cmbox_activation)
        self.but_send = QPushButton(self.splitter_3)
        self.but_send.setObjectName(u"but_send")
        self.but_send.setEnabled(True)
        icon1 = QIcon()
        icon1.addFile(u"image/\u53d1\u9001_send.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_send.setIcon(icon1)
        self.splitter_3.addWidget(self.but_send)
        self.but_double_cha = QPushButton(self.splitter_3)
        self.but_double_cha.setObjectName(u"but_double_cha")
        icon2 = QIcon()
        icon2.addFile(u"image/\u90ae\u4ef6\u7b26\u53f7_at-sign.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_double_cha.setIcon(icon2)
        self.splitter_3.addWidget(self.but_double_cha)
        self.but_monitor = QPushButton(self.splitter_3)
        self.but_monitor.setObjectName(u"but_monitor")
        self.but_monitor.setEnabled(True)
        icon3 = QIcon()
        icon3.addFile(u"image/\u773c\u775b_eyes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_monitor.setIcon(icon3)
        self.splitter_3.addWidget(self.but_monitor)
        self.but_monitor2 = QPushButton(self.splitter_3)
        self.but_monitor2.setObjectName(u"but_monitor2")
        self.but_monitor2.setIcon(icon3)
        self.splitter_3.addWidget(self.but_monitor2)
        self.but_sign = QPushButton(self.splitter_3)
        self.but_sign.setObjectName(u"but_sign")
        self.but_sign.setEnabled(True)
        icon4 = QIcon()
        icon4.addFile(u"image/\u70b9\u51fb_click-tap.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_sign.setIcon(icon4)
        self.splitter_3.addWidget(self.but_sign)
        self.splitter = QSplitter(self.splitter_3)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.input_shortcut = QLineEdit(self.splitter)
        self.input_shortcut.setObjectName(u"input_shortcut")
        self.splitter.addWidget(self.input_shortcut)
        self.but_shortcut = QPushButton(self.splitter)
        self.but_shortcut.setObjectName(u"but_shortcut")
        icon5 = QIcon()
        icon5.addFile(u"image/\u4fe1\u606f_message.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_shortcut.setIcon(icon5)
        self.splitter.addWidget(self.but_shortcut)
        self.but_exit = QPushButton(self.splitter)
        self.but_exit.setObjectName(u"but_exit")
        icon6 = QIcon()
        icon6.addFile(u"image/\u9000\u51fa_logout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_exit.setIcon(icon6)
        self.splitter.addWidget(self.but_exit)
        self.but_more = QPushButton(self.splitter)
        self.but_more.setObjectName(u"but_more")
        self.but_more.setEnabled(True)
        icon7 = QIcon()
        icon7.addFile(u"image/\u7ffb\u8bd1_translation.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_more.setIcon(icon7)
        self.splitter.addWidget(self.but_more)
        self.splitter_3.addWidget(self.splitter)
        self.splitter_4 = QSplitter(Form)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(10, 310, 226, 41))
        self.splitter_4.setOrientation(Qt.Horizontal)
        self.layoutWidget = QWidget(self.splitter_4)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMaximumSize(QSize(50, 16777215))
        self.label_5.setAutoFillBackground(True)
        self.label_5.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label_5)

        self.spinBox_setp = QSpinBox(self.layoutWidget)
        self.spinBox_setp.setObjectName(u"spinBox_setp")
        self.spinBox_setp.setMaximumSize(QSize(16777215, 20))
        self.spinBox_setp.setAutoFillBackground(True)
        self.spinBox_setp.setMinimum(1)
        self.spinBox_setp.setMaximum(10000)

        self.verticalLayout.addWidget(self.spinBox_setp)

        self.splitter_4.addWidget(self.layoutWidget)
        self.layoutWidget1 = QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.layoutWidget1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QSize(50, 16777215))
        self.label_2.setAutoFillBackground(True)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_2)

        self.spinBox_time = QSpinBox(self.layoutWidget1)
        self.spinBox_time.setObjectName(u"spinBox_time")
        self.spinBox_time.setMaximum(999999)

        self.verticalLayout_2.addWidget(self.spinBox_time)

        self.splitter_4.addWidget(self.layoutWidget1)
        self.layoutWidget2 = QWidget(self.splitter_4)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.layoutWidget2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMaximumSize(QSize(50, 16777215))
        self.label_6.setAutoFillBackground(True)
        self.label_6.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_6)

        self.spinBox_numb = QSpinBox(self.layoutWidget2)
        self.spinBox_numb.setObjectName(u"spinBox_numb")
        self.spinBox_numb.setMaximumSize(QSize(16777215, 20))
        self.spinBox_numb.setAutoFillBackground(True)
        self.spinBox_numb.setMinimum(1)
        self.spinBox_numb.setMaximum(99)

        self.verticalLayout_3.addWidget(self.spinBox_numb)

        self.splitter_4.addWidget(self.layoutWidget2)
        self.layoutWidget3 = QWidget(self.splitter_4)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.layoutWidget3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.label_4)

        self.spinBox_quci = QSpinBox(self.layoutWidget3)
        self.spinBox_quci.setObjectName(u"spinBox_quci")

        self.verticalLayout_4.addWidget(self.spinBox_quci)

        self.splitter_4.addWidget(self.layoutWidget3)
        self.chk_id = QCheckBox(Form)
        self.chk_id.setObjectName(u"chk_id")
        self.chk_id.setGeometry(QRect(355, 310, 71, 20))
        self.layoutWidget4 = QWidget(Form)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(69, 10, 413, 57))
        self.gridLayout = QGridLayout(self.layoutWidget4)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.but_add_config = QPushButton(self.layoutWidget4)
        self.but_add_config.setObjectName(u"but_add_config")
        self.but_add_config.setEnabled(True)
        self.but_add_config.setMinimumSize(QSize(55, 55))
        self.but_add_config.setMaximumSize(QSize(55, 16777215))

        self.gridLayout.addWidget(self.but_add_config, 0, 2, 1, 1)

        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.splitter_5 = QSplitter(self.layoutWidget4)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.label_key = QLabel(self.splitter_5)
        self.label_key.setObjectName(u"label_key")
        self.label_key.setAlignment(Qt.AlignCenter)
        self.splitter_5.addWidget(self.label_key)
        self.text_key = QLineEdit(self.splitter_5)
        self.text_key.setObjectName(u"text_key")
        self.splitter_5.addWidget(self.text_key)

        self.verticalLayout_5.addWidget(self.splitter_5)

        self.splitter_6 = QSplitter(self.layoutWidget4)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.label_value = QLabel(self.splitter_6)
        self.label_value.setObjectName(u"label_value")
        self.label_value.setAlignment(Qt.AlignCenter)
        self.splitter_6.addWidget(self.label_value)
        self.text_value = QLineEdit(self.splitter_6)
        self.text_value.setObjectName(u"text_value")
        self.splitter_6.addWidget(self.text_value)

        self.verticalLayout_5.addWidget(self.splitter_6)


        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)

        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.cmbox_config = QComboBox(self.layoutWidget4)
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        self.cmbox_config.addItem("")
        icon8 = QIcon()
        icon8.addFile(u"image/\u661f\u661f_star.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cmbox_config.addItem(icon8, "")
        self.cmbox_config.addItem(icon8, "")
        self.cmbox_config.addItem(icon8, "")
        self.cmbox_config.addItem(icon8, "")
        self.cmbox_config.setObjectName(u"cmbox_config")
        self.cmbox_config.setAcceptDrops(False)

        self.verticalLayout_6.addWidget(self.cmbox_config)

        self.but_add_config_key = QPushButton(self.layoutWidget4)
        self.but_add_config_key.setObjectName(u"but_add_config_key")
        icon9 = QIcon()
        icon9.addFile(u"image/\u6dfb\u52a0\u5217\u8868_list-add.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_add_config_key.setIcon(icon9)

        self.verticalLayout_6.addWidget(self.but_add_config_key)


        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)

        self.layoutWidget5 = QWidget(Form)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(69, 70, 413, 26))
        self.gridLayout_2 = QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.but_del_dict = QPushButton(self.layoutWidget5)
        self.but_del_dict.setObjectName(u"but_del_dict")
        icon10 = QIcon()
        icon10.addFile(u"image/\u5220\u9664_delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_del_dict.setIcon(icon10)

        self.gridLayout_2.addWidget(self.but_del_dict, 0, 2, 1, 1)

        self.cmbox_revise = QComboBox(self.layoutWidget5)
        self.cmbox_revise.setObjectName(u"cmbox_revise")
        self.cmbox_revise.setMinimumSize(QSize(80, 0))
        self.cmbox_revise.setMaximumSize(QSize(80, 16777215))

        self.gridLayout_2.addWidget(self.cmbox_revise, 0, 0, 1, 1)

        self.but_save_config = QPushButton(self.layoutWidget5)
        self.but_save_config.setObjectName(u"but_save_config")
        self.but_save_config.setEnabled(True)
        icon11 = QIcon()
        icon11.addFile(u"image/\u4fdd\u5b58_save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_save_config.setIcon(icon11)

        self.gridLayout_2.addWidget(self.but_save_config, 0, 4, 1, 1)

        self.but_del_key1 = QPushButton(self.layoutWidget5)
        self.but_del_key1.setObjectName(u"but_del_key1")
        icon12 = QIcon()
        icon12.addFile(u"image/\u6e05\u9664_clear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_del_key1.setIcon(icon12)

        self.gridLayout_2.addWidget(self.but_del_key1, 0, 1, 1, 1)

        self.but_red_config = QPushButton(self.layoutWidget5)
        self.but_red_config.setObjectName(u"but_red_config")
        icon13 = QIcon()
        icon13.addFile(u"image/\u8bbe\u7f6e\u914d\u7f6e_setting-config.png", QSize(), QIcon.Normal, QIcon.Off)
        self.but_red_config.setIcon(icon13)

        self.gridLayout_2.addWidget(self.but_red_config, 0, 3, 1, 1)

        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(8, 74, 55, 21))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet(u"")
        self.label_7.setScaledContents(True)
        self.label_7.setOpenExternalLinks(True)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(6, 10, 60, 60))
        self.label_8.setMinimumSize(QSize(60, 60))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet(u"")
        self.label_8.setPixmap(QPixmap(u"image/logo2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setOpenExternalLinks(True)
        self.layoutWidget1.raise_()
        self.splitter_4.raise_()
        self.splitter_3.raise_()
        self.chk_taici.raise_()
        self.pushButton_11.raise_()
        self.label.raise_()
        self.but_wallet.raise_()
        self.layoutWidget1.raise_()
        self.print_1.raise_()
        self.print_2.raise_()
        self.chk_translate.raise_()
        self.but_cls_logtotext_2.raise_()
        self.but_save_logtotext.raise_()
        self.but_cls_kwsms.raise_()
        self.print_4.raise_()
        self.but_daiban.raise_()
        self.chk_id.raise_()
        self.label_7.raise_()
        self.label_8.raise_()

        self.retranslateUi(Form)
        self.cmbox_config.currentTextChanged.connect(self.label_key.setText)
        self.input_shortcut.returnPressed.connect(self.but_shortcut.animateClick)
        self.text_value.returnPressed.connect(self.but_add_config.animateClick)
        self.text_key.returnPressed.connect(self.but_add_config.animateClick)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u6631\u5cf0\u4e2d\u6587Discord Tools V8.0 |\u5fae\u4fe1\uff1aYufeng0736520", None))
        self.but_cls_logtotext_2.setText(QCoreApplication.translate("Form", u"CL", None))
        self.but_save_logtotext.setText(QCoreApplication.translate("Form", u"\u5b58", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u5173\u952e\u5b57\u4fe1\u606f-->", None))
        self.but_cls_kwsms.setText(QCoreApplication.translate("Form", u"CL", None))
        self.but_wallet.setText(QCoreApplication.translate("Form", u"\u94b1\u5305", None))
        self.chk_translate.setText(QCoreApplication.translate("Form", u"\u4e2d-->\u82f1", None))
#if QT_CONFIG(tooltip)
        self.chk_taici.setToolTip(QCoreApplication.translate("Form", u"\u52fe\u9009\u662f\u4ece\u63d0\u53d6\u5217\u8868\u53d6\u53f0\u8bcd\u53d1\u9001\uff0c\u4e0d\u52fe\u9009\u662f\u81ea\u5b9a\u4e49\u53f0\u8bcd", None))
#endif // QT_CONFIG(tooltip)
        self.chk_taici.setText(QCoreApplication.translate("Form", u"\u53d6\u8bcd\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.pushButton_11.setToolTip(QCoreApplication.translate("Form", u"\u6253\u5f00\u81ea\u5b9a\u4e49\u53f0\u8bcd\u672c\uff0c\u6ca1\u6709\u5c31\u521b\u5efa\u4e00\u4e2a\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_11.setText(QCoreApplication.translate("Form", u"\u8bcd", None))
        self.but_daiban.setText(QCoreApplication.translate("Form", u"\u5f85", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u6fc0\u6d3b\u9891\u9053->", None))
        self.cmbox_activation.setPlaceholderText(QCoreApplication.translate("Form", u"\u9891\u9053\u5217\u8868", None))
#if QT_CONFIG(tooltip)
        self.but_send.setToolTip(QCoreApplication.translate("Form", u"\u5faa\u73af\u53d1\u9001\u4fe1\u606f\u5230\u9009\u62e9\u5217\u8868\uff0c\u6709\u4e24\u79cd\u6a21\u5f0f\uff0c\u81ea\u5b9a\u4e49\u53f0\u8bcd\u548c\u63d0\u53d6\u53f0\u8bcd", None))
#endif // QT_CONFIG(tooltip)
        self.but_send.setText(QCoreApplication.translate("Form", u"\u7fa4\u53d1[run]", None))
        self.but_double_cha.setText(QCoreApplication.translate("Form", u"\u4ea4\u4e92[run]", None))
#if QT_CONFIG(tooltip)
        self.but_monitor.setToolTip(QCoreApplication.translate("Form", u"\u65e0\u9650\u5faa\u73af\u76d1\u63a7\u9009\u62e9\u9891\u9053\u5217\u8868\u4e2d\u6240\u6709\u4fe1\u606f\uff0c\u81ea\u52a8\u8fc7\u6ee4\u5173\u952e\u5b57", None))
#endif // QT_CONFIG(tooltip)
        self.but_monitor.setText(QCoreApplication.translate("Form", u"\u76d1\u63a7[run]", None))
        self.but_monitor2.setText(QCoreApplication.translate("Form", u"\u76d1\u63a7[run]", None))
#if QT_CONFIG(tooltip)
        self.but_sign.setToolTip(QCoreApplication.translate("Form", u"\u7ed9\u9009\u62e9\u7684\u9891\u9053\u5217\u8868\u53d1\u9001\u4e00\u6761\u4fe1\u606f\uff0c\u4e0d\u662f\u5faa\u73af\u53d1\uff0c\u8fd9\u6837\u66f4\u65b9\u4fbf\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.but_sign.setText(QCoreApplication.translate("Form", u"\u7b7e\u5230", None))
#if QT_CONFIG(tooltip)
        self.input_shortcut.setToolTip(QCoreApplication.translate("Form", u"\u53cc\u51fb\u804a\u5929\u5185\u5bb9\u94fe\u63a5\u4e2d\u7684\u9891\u9053id\uff0c\u8f93\u5165\u5185\u5bb9\u53ef\u4ee5\u53d1\u9001\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.input_shortcut.setPlaceholderText(QCoreApplication.translate("Form", u"\u8f93\u5165\u5185\u5bb9\u53ef\u4ee5\u53d1\u4fe1\u606f\u5230\u9891\u9053", None))
#if QT_CONFIG(tooltip)
        self.but_shortcut.setToolTip(QCoreApplication.translate("Form", u"\u53f3\u4fa7\u8f93\u5165\u5185\u5bb9\uff0c\u56de\u8f66\u53d1\u9001\u5230\u9009\u5b9a\u7684\u9891\u9053\u3002\u5185\u5bb9\u8bb0\u5f55\u91cc\u9762\u53cc\u51fb\u9891\u9053id\u53ef\u4ee5\u9009\u5b9a\u53d1\u9001\u7684\u9891\u9053", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.but_shortcut.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.but_shortcut.setText(QCoreApplication.translate("Form", u"\u5feb\u6377\u56de\u590d", None))
        self.but_exit.setText(QCoreApplication.translate("Form", u"\u9000\u51fa", None))
        self.but_more.setText(QCoreApplication.translate("Form", u"\u7ffb\u8bd1", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u95f4\u9694[\u79d2]", None))
#if QT_CONFIG(tooltip)
        self.spinBox_setp.setToolTip(QCoreApplication.translate("Form", u"\u53d1\u9001\u4fe1\u606f\u95f4\u9694\u7684\u65f6\u95f4", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("Form", u"\u65f6\u6548[\u65f6]", None))
#if QT_CONFIG(tooltip)
        self.spinBox_time.setToolTip(QCoreApplication.translate("Form", u"\u76d1\u63a7\u6a21\u5f0f\u63d0\u53d6\u4fe1\u606f\u7684\u65f6\u6548", None))
#endif // QT_CONFIG(tooltip)
        self.label_6.setText(QCoreApplication.translate("Form", u"\u4fe1\u606f\u6761\u6570", None))
#if QT_CONFIG(tooltip)
        self.spinBox_numb.setToolTip(QCoreApplication.translate("Form", u"\u76d1\u63a7\u6a21\u5f0f\u6709\u6548\u63d0\u53d6\u9891\u9053\u7684\u4fe1\u606f\u6570\uff0c\u6700\u592799", None))
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("Form", u"\u63d0\u8bcd\u9891\u9053", None))
#if QT_CONFIG(tooltip)
        self.spinBox_quci.setToolTip(QCoreApplication.translate("Form", u"\u9009\u62e9\u4e00\u4e2a\u9891\u9053\u4f5c\u4e3a\u53d1\u9001\u6d88\u606f\u65f6\u63d0\u53d6\u5185\u5bb9\u7684\u9891\u9053", None))
#endif // QT_CONFIG(tooltip)
        self.chk_id.setText(QCoreApplication.translate("Form", u"\u5355\u53f7\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.but_add_config.setToolTip(QCoreApplication.translate("Form", u"\u6dfb\u52a0\u540e\u81ea\u52a8\u4fdd\u5b58", None))
#endif // QT_CONFIG(tooltip)
        self.but_add_config.setText(QCoreApplication.translate("Form", u"\u6dfb\u52a0", None))
        self.label_key.setText(QCoreApplication.translate("Form", u"\u9891\u9053\u540d\u79f0", None))
        self.text_key.setPlaceholderText("")
        self.label_value.setText(QCoreApplication.translate("Form", u"\u9891\u9053\u94fe\u63a5", None))
        self.cmbox_config.setItemText(0, QCoreApplication.translate("Form", u"\u793e\u533a\u516c\u544a", None))
        self.cmbox_config.setItemText(1, QCoreApplication.translate("Form", u"\u793e\u533a\u804a\u5929", None))
        self.cmbox_config.setItemText(2, QCoreApplication.translate("Form", u"\u4f18\u8d28\u9879\u76ee", None))
        self.cmbox_config.setItemText(3, QCoreApplication.translate("Form", u"\u666e\u901a\u9879\u76ee", None))
        self.cmbox_config.setItemText(4, QCoreApplication.translate("Form", u"\u4f5c\u4e1a\u9891\u9053", None))
        self.cmbox_config.setItemText(5, QCoreApplication.translate("Form", u"OG\u9891\u9053", None))
        self.cmbox_config.setItemText(6, QCoreApplication.translate("Form", u"\u9080\u8bf7\u5206\u4eab", None))
        self.cmbox_config.setItemText(7, QCoreApplication.translate("Form", u"\u5783\u573e\u5e7f\u544a", None))
        self.cmbox_config.setItemText(8, QCoreApplication.translate("Form", u"\u5907\u7528\u9891\u9053", None))
        self.cmbox_config.setItemText(9, QCoreApplication.translate("Form", u"\u63d0\u8bcd\u4e13\u7528", None))
        self.cmbox_config.setItemText(10, QCoreApplication.translate("Form", u"\u5173\u952e\u5b57\u8868", None))
        self.cmbox_config.setItemText(11, QCoreApplication.translate("Form", u"\u6388\u6743\u8d26\u53f7", None))
        self.cmbox_config.setItemText(12, QCoreApplication.translate("Form", u"\u4ee3\u7406\u8bbe\u7f6e", None))

#if QT_CONFIG(tooltip)
        self.cmbox_config.setToolTip(QCoreApplication.translate("Form", u"\u9009\u62e9\u9700\u8981\u6dfb\u52a0\u7684\u9891\u9053\u5217\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.cmbox_config.setPlaceholderText(QCoreApplication.translate("Form", u"\u9009\u62e9\u7c7b\u522b", None))
#if QT_CONFIG(tooltip)
        self.but_add_config_key.setToolTip(QCoreApplication.translate("Form", u"\u4e34\u65f6\u589e\u52a0\u4e00\u4e2a\u914d\u7f6e\u7c7b\u522b\uff0c\u4fbf\u4e8e\u9891\u9053\u5206\u7c7b", None))
#endif // QT_CONFIG(tooltip)
        self.but_add_config_key.setText(QCoreApplication.translate("Form", u"\u589e\u52a0\u7c7b\u522b", None))
        self.but_del_dict.setText(QCoreApplication.translate("Form", u"\u5220\u9664\u914d\u7f6e", None))
#if QT_CONFIG(tooltip)
        self.cmbox_revise.setToolTip(QCoreApplication.translate("Form", u"\u8fd9\u91cc\u53ef\u4ee5\u5220\u9664\u5173\u952e\u5b57\u548c\u4ee3\u7406", None))
#endif // QT_CONFIG(tooltip)
        self.cmbox_revise.setPlaceholderText(QCoreApplication.translate("Form", u"\u4fee\u6539\u5b57\u5178", None))
        self.but_save_config.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58\u914d\u7f6e", None))
#if QT_CONFIG(tooltip)
        self.but_del_key1.setToolTip(QCoreApplication.translate("Form", u"\u6e05\u7a7a\u5173\u6ce8\u9891\u9053\u5217\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.but_del_key1.setText(QCoreApplication.translate("Form", u"\u5220\u9664\u9891\u9053", None))
        self.but_red_config.setText(QCoreApplication.translate("Form", u"\u8bfb\u53d6\u914d\u7f6e", None))
        self.label_7.setText("")
        self.label_8.setText("")
    # retranslateUi

